### ISSUE TITLE
[MySQL] cannot initialize database

### ISSUE THREAD

**Issue by blacknred0** [wavexx/dl#23]
I found this issue (https://github.com/wavexx/dl/issues/3) with sqlite3 and tried to follow as much as I could with MySQL, but I still have issues when trying to access the site.

Any thoughts as of what it could be?  I am using 1&1 Shared Hosting.  Which it means that I am currently lacking of sudo access.  I can connect to the db with no problem through php with the test files that I created.

**Comment by wavexx** [comment]
On 02/18/2015 08:16 PM, blacknred0 wrote:
> I found this issue (https://github.com/wavexx/dl/issues/3) with
> sqlite3 and tried to follow as much as I could with MySQL, but I
> still have issues when trying to access the site.
> 
> Any thoughts as of what it could be?  I am using 1&1 Shared Hosting.
> Which it means that I am currently lacking of sudo access.  I can
> connect to the db with no problem through php with the test files
> that I created.

Anything in the log files?

**Comment by blacknred0** [comment]
I couldn't get the logs in PHP, but I did some more digging and in the end, I was able to figure it out. 

I was using the variables from this documentation -> http://php.net/manual/en/ref.pdo-mysql.connection.php
```
<?php
$dsn = 'mysql:host=localhost;dbname=testdb';
$username = 'username';
$password = 'password';
$options = array(
    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
); 

$dbh = new PDO($dsn, $username, $password, $options);
?>
```
but, once I changed the variables $username/$password to $dbUser/$dbPassword everything worked.
```
<?php
$dsn = 'mysql:host=localhost;dbname=testdb';
$dbUser = 'username';
$dbPassword = 'password';
$options = array(
    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
); 

$dbh = new PDO($dsn, $dbUser, $dbPassword, $options);
?>
```
