### ISSUE TITLE
Thunderbird An error occurred while setting up the account! when working with dl-wx

### ISSUE THREAD

**Issue by blacknred0** [wavexx/dl#24]
So, I finally was able to create the account on the website and install the add-on in Ubuntu 14.04 using Thunderbird 34.1.0.  I follow the steps from the tutorial by installing all of the required software.  When I go to Thunderbird and input my REST URL, username, and password; I get the following error in Thunderbird -> "An error occurred while setting up the account!".  I checked Thunderbird "Error console" and it is really not giving me any information about the failure.  Per documentation [from this link -> http://www.thregr.org/~wavexx/software/dl/thunderbird.html], I check and 1 & 2 under "Troubleshooting" seem ok. Specially that I do get a blank page when I visit my site.com/rest.php.

Things to point out... I do not have any server certificate (so everything is unencrypted) and I don't know if the problem might be that the Graphical client (dl-wx) is not running properly on my Ubuntu machine, since I do not see any the DL application in my taskbar.  I am using Python 2.7

Ref link that I used
http://article.gmane.org/gmane.comp.web.dl-ticket-service.general/268

**Comment by wavexx** [comment]
On 02/19/2015 04:19 PM, blacknred0 wrote:
> So, I finally was able to create the account on the website and
> install the add-on in Ubuntu 14.04 using Thunderbird 34.1.0.  I
> follow the steps from the tutorial by installing all of the required
> software.  When I go to Thunderbird and input my REST URL, username,
> and password; I get the following error in Thunderbird -> "An error
> occurred while setting up the account!".  I checked Thunderbird
> "Error console" and it is really not giving me any information about
> the failure.  Per documentation [from this link ->
> http://www.thregr.org/~wavexx/software/dl/thunderbird.html], I check
> and 1 & 2 under "Troubleshooting" seem ok. Specially that I do get a
> blank page when I visit my site.com/rest.php.
> 
> Things to point out... I do not have any server certificate (so
> everything is unencrypted) and I don't know if the problem might be
> that the Graphical client (dl-wx) is not running properly on my
> Ubuntu machine, since I do not see any the DL application in my
> taskbar.  I am using Python 2.7

I don't understand from the subject if dl-wx works or not in your case.

Did you check the apache's and PHP's error_log?

**Comment by blacknred0** [comment]
I don't see dl-wx in my task bar, so my assumption is that it is not
working.  Is there a way to check in Ubuntu?  I did check the logs in
the end server and didn't see anything over there worth noting.

Thanks for your help so far.

Thank you,

Irving Duran

**Comment by wavexx** [comment]
On 02/19/2015 04:32 PM, blacknred0 wrote:
> I don't see dl-wx in my task bar, so my assumption is that it is not
> working.  Is there a way to check in Ubuntu?  I did check the logs in

dl-wx should ask for username/password the first time.
What happens when you run it from the command line?

    cd dl/client/dl-wx
    ./dl-wx.py

> the end server and didn't see anything over there worth noting.

In config.php, set $logFile to a valid filename.
In the web interface, create a ticket and download it.
See that the log file contains two lines (ticket creation and download).
When it works, try to setup thunderbird again and check this file.

**Comment by blacknred0** [comment]
> dl-wx should ask for username/password the first time.
> What happens when you run it from the command line?
I did get the initial setup of username/password.  When I run it from
the command line. I get nothing.

I tried  ./dl-wx.py and python -v dl-wx.py.  When I do it verbosely, it
looks like every loaded correctly.

> In config.php, set $logFile to a valid filename.
> In the web interface, create a ticket and download it.
> See that the log file contains two lines (ticket creation and download).
> When it works, try to setup thunderbird again and check this file.

I looks that it successfully uploaded the file, but not when I download
it.  I've been trying to configure my htaccess to work with the
PATH_INFO and I think that since this is a share hosting with 1&1, I am
having some limitations as of what I can do.  Not sure if you or
somebody has any ideas in this space.  Otherwise, I might try this
software on my local server instead.

[Thu, 19 Feb 2015 12:47:30 -0500] admin:
t/01e855c8c9276e99a24b3b27a36d09c7 (test.txt): temporary ticket created
[Thu, 19 Feb 2015 12:47:32 -0500] admin: error: missing PATH_INFO,
cannot continue

Thank you,

Irving Duran

**Comment by wavexx** [comment]
On 02/19/2015 06:58 PM, blacknred0 wrote:
> I tried  ./dl-wx.py and python -v dl-wx.py.  When I do it verbosely, it
> looks like every loaded correctly.

Does ~/.dl.rc exists?

On the first run (when the file is missing) a request for the REST
url/username/password should be shown.

> I looks that it successfully uploaded the file, but not when I download
> it.  I've been trying to configure my htaccess to work with the
> PATH_INFO and I think that since this is a share hosting with 1&1, I am
> having some limitations as of what I can do.  Not sure if you or
> somebody has any ideas in this space.  Otherwise, I might try this
> software on my local server instead.
> 
> [Thu, 19 Feb 2015 12:47:30 -0500] admin:
> t/01e855c8c9276e99a24b3b27a36d09c7 (test.txt): temporary ticket created
> [Thu, 19 Feb 2015 12:47:32 -0500] admin: error: missing PATH_INFO,

This is definitely going to be a problem anyway. PATH_INFO is required
for proper operation.

Try to see if you can set AcceptPathInfo directly in your .htaccess.

I would also recommend trying DL locally first, especially to setup your
client. Shared hosting providers tend to ship with old php versions, bad
defaults and disable certain modules. I honestly cannot debug every
hosting provider on earth.

**Comment by blacknred0** [comment]
Yes the ~.dl.rc exists and the rest URL, username, and password is there
as well.

Thanks for your suggestion, I tried AcceptPathInfo in my .htaccess and
didn't work.  I also reached to the shared server provider and they
mention that I am only allowed to do it on the files and not directories
(since this is a shared environment).  Not sure why :/.

I don't think it is expected for you to test every hosting provider in
the world.  I like what I see, so I am going to try and configure it on
my local server instead.

Thanks for your help.  I'll leave it up to you if you want to close this
or keep it open as an enhancement for future releases if possible.

**Comment by wavexx** [comment]
On 02/20/2015 08:51 PM, blacknred0 wrote:
> Thanks for your suggestion, I tried AcceptPathInfo in my .htaccess and
> didn't work.  I also reached to the shared server provider and they
> mention that I am only allowed to do it on the files and not directories
> (since this is a shared environment).  Not sure why :/.

Then try to enable it for "d.php" and "rest.php"

> I don't think it is expected for you to test every hosting provider in
> the world.  I like what I see, so I am going to try and configure it on
> my local server instead.

The problem with hosting providers is that they often add arbitrary
restrictions such as AcceptPathInfo which is by itself harmless. By
experience, they do this to fix vulnerabilities of wordpress or common
PHP packages sitewide, without requiring the owner to update (since the
owner is often clueless). Needless to say, you often need to workaround
a lot of this stuff.

**Comment by blacknred0** [comment]
Tried your suggestion and been debugging to see if I could make it work on this shared environment [and even tried <Files *.php> ######## </Files> on my .htaccess] and so far no hope.  I will keep trying here and there, but for now, I just installed on my local server and it worked perfectly so far.

Thanks for the great piece of work.

**Comment by wavexx** [comment]
On 02/25/2015 03:15 AM, blacknred0 wrote:
> Tried your suggestion and been debugging to see if I could make it
> work on this shared environment [and even tried <Files *.php>

Note that for apache, a valid config block would be:

<FilesMatch "^(d|rest).php$">
   AcceptPathInfo On
</FilesMatch>

A global "AcceptPathInfo on" is suggested in the configuration, but the
above should work. If you still get the message about PATH_INFO missing
on the log, then the hosting service probably does something else as
well. Without looking at the entire apache configuration, this is *very*
difficult to guess.

> trying here and there, but for now, I just installed on my local
> server and it worked perfectly so far.

I would just ask the hosting company to provide detailed information
about the web server and php settings (though for php you could just use
phpinfo()).

You might eventually find that they limit upload sizes or timeouts to
ridiculous amounts anyway....

**Comment by wavexx** [comment]
News?

**Comment by blacknred0** [comment]
No good news.  I've been working with them, but no results.
Here is what I got, but when I enable them, still get the same issue.

"You can only enable the  AcceptPathInfo through .htaccess file. The AcceptPathInfo is not included in the PHP directives."

I think we can consider this issue closed due to the challanges with a
hosted shared environment.

Thank you,

Irving Duran

**Comment by wavexx** [comment]
Sad to hear this. Given that this cannot be easily fixed without breaking the entire REST protocol, I'll close the issue.
