### ISSUE TITLE
Add failed

### ISSUE THREAD

**Issue by RustyPixel** [wavexx/dl#25]
It would be nice to add failed logging attempts that can be used with fail2ban.

**Comment by wavexx** [comment]
On 03/01/2015 10:58 PM, RustyPixel wrote:
> It would be nice to add failed logging attempts that can be used with fail2ban.

I added an entry for login attempts.
Could you check if this is enough?

**Comment by RustyPixel** [comment]
Had to change https://github.com/wavexx/dl/blob/master/htdocs/include/funcs.php#L37
```     $logLine = "[" . date("Y/m/d H:m:s") . "] $logLine\n"; ``` 
f2b didn't like orginal

https://github.com/wavexx/dl/blob/master/htdocs/include/admfuncs.php#L285

```   logEvent("Login from ".$_SERVER["REMOTE_ADDR"]." for user $user " . ($ret? "success": "failed")); ```

need remote ip to ban

**Comment by wavexx** [comment]
On 03/03/2015 04:45 PM, RustyPixel wrote:
> Had to change https://github.com/wavexx/dl/blob/master/htdocs/include/funcs.php#L37
> ```     $logLine = "[" . date("Y/m/d H:m:s") . "] $logLine\n"; ``` 
> f2b didn't like orginal

If I need to change the log format, I would use DATE_W3C
(2005-08-15T15:52:01+00:00) instead. Would that be fine for f2b?

**Comment by RustyPixel** [comment]
Yes that works but look at the diff in output
``` [2015/03/03 15:03:17] Login from 0.0.0.0 for user admin failed ```
``` [2015-03-03T16:19:26+00:00] Login from 0.0.0.0 for user sad failed ```

**Comment by wavexx** [comment]
On 03/03/2015 05:22 PM, RustyPixel wrote:
> Yes that works but look at the diff in output
> ``` [2015/03/03 15:03:17] Login from 0.0.0.0 for user admin failed ```
> ``` [2015-03-03T16:19:26+00:00] Login from 0.0.0.0 for user sad failed ```

It's longer because of the timezone, which is good to have.

rsyslog is using mostly the same format (plus second fractions), and
many others. I don't think it's an issue given how infrequent this log
is appended to.

**Comment by RustyPixel** [comment]
No issues both work and my main goal was since it use's logging many as well have f2b use it.

**Comment by RustyPixel** [comment]
Here is f2b 0.9 running on py3 

settings jail.local is 
```
[dlticket]
enabled = true
filter = dlticket
port     = http,https
logpath  = /PATH TO/*ticket*.log
```

filter.d/dlticket.conf
```
[Definition]
failregex = ^\[\] Login from <HOST> for user .* failed

```
many need some extra work but here is a starting point.

**Comment by wavexx** [comment]
On 03/03/2015 05:29 PM, RustyPixel wrote:
> No issues both work and my main goal was since it use's logging many
> as well have f2b use it.

Committed.

Note that the final format is:

[2015-03-03T19:46:55+01:00] [127.0.0.1] login attempt for user x: fail

The IP address is always prepended as [addr] before the log line if it
is available (all REST requests use this format already and I will be
switching the others as I run through them).

**Comment by RustyPixel** [comment]
Sorry for late replay just got round to setting f2b with new setting in filter.d/dlticket.conf
```
failregex = ^\[\] error: \[<HOST>\] login attempt for user .*: fail
```
Output ( ignore result 1 as i have both from my test in log file still)
```
~ $ sudo fail2ban-regex /PATH/www/dlticket/.data/ticket.log  /etc/fail2ban/filter.d/dlticket.conf

Running tests
=============

Use   failregex file : /etc/fail2ban/filter.d/dlticket.conf
Use         log file : /PATH/www/dlticket/.data/ticket.log
Use         encoding : UTF-8


Results
=======

Failregex: 5 total
|-  #) [# of hits] regular expression
|   1) [4] ^\[\] Login from <HOST> for user .* failed
|   2) [1] ^\[\] error: \[<HOST>\] login attempt for user .*: fail
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
|  [4] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
`-
```

all whats need is create a f2b how to and this can be closed. nice job and thanks :smile:

**Comment by wavexx** [comment]
Looks good, closing this.
