### ISSUE TITLE
Thunderbird 38.0.1 + Add-On 0.13 stopped working

### ISSUE THREAD

**Issue by sudokuqt4** [wavexx/dl#28]
After updating Thunderbird to 38 from 31 the add-on 0.13 hangs on upload with the wait icon being displayed. Error log has these two entries:

ReferenceError: File is not defined
File: jar:file:///.../extensions/thunderbird-filelink-dl@thregr.org.xpi!/components/nsDL.js
Line: 104

ReferenceError: listener is not defined
File: chrome://messenger/content/messengercompose/MsgComposeCommands.js
Line: 1450

I sadly can't tell if those are related to the issue.

**Comment by wavexx** [comment]
On 06/23/2015 08:55 PM, D. Sessler wrote:
> After updating Thunderbird to 38 from 31 the add-on 0.13 hangs on
> upload with the wait icon being displayed. Error log has these two
> entries:
> 
> ReferenceError: File is not defined File:
> jar:file:///.../extensions/thunderbird-filelink-dl@thregr.org.xpi!/components/nsDL.js

Very detailed report, thanks.

Updating to TB 38 to see what's going on..

**Comment by wavexx** [comment]
I was able to fix it, could you please try this new version:

http://www.thregr.org/~wavexx/tmp/thunderbird-filelink-dl-0.17rc1.xpi

and report if it works? It would be nice if you could also test it on older versions of Thunderbird as well (it should, but testing doesn't hurt before releasing).

**Comment by sudokuqt4** [comment]
Thanks for the quick fix. Here's my test result:

Works with 38.0.1.

Doesn't work with 31.7.0: After updating the add-on from 0.13 DL doesn't show up as a filelink provider in the settings. After updating Thunderbird to 38 DL reappeared.

**Comment by wavexx** [comment]
Let's try again:

http://www.thregr.org/~wavexx/tmp/thunderbird-filelink-dl-0.17rc2.xpi

This should work on all versions now.

**Comment by sudokuqt4** [comment]
Works with 38.0.1 and 31.7.0.

Thank you very much!

**Comment by wavexx** [comment]
I submitted 0.17 to be reviewed, so It's going to end up to appear on AMO eventually in the next days/a week.
